apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: imran7012/order-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: USERS_URL
              value: http://user-service:3000
            - name: PRODUCTS_URL
              value: http://product-service:3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3002
          #   initialDelaySeconds: 15
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3002
          #   initialDelaySeconds: 5
